version: '4'
services:
  server: 
    build: .
    container_name: server
    command: "rails server -b 0.0.0.0"
    volumes:
      - ./:/usr/src/
    environment:
      PORT: 3002
    ports:
      - 3002:3002
    depends_on:
      - mysql
  
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: percona:8-centos
    environment:
      MYSQL_ROOT_PASSWORD: password 
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: