version: '4'
services:
  server: 
    build: .
    command: "rails server -b 0.0.0.0"
    volumes:
      - ./:/usr/src/
    environment:
      PORT: 3002
    ports:
      - 3002:3002
    depends_on:
      - db
  
  db:
    image: mysql2
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
    volumes:
      - mysql2:/var/lib/mysql2/data

volumes:
  mysql2: